apiVersion: "datacater.io/v1"
kind: "Pipeline"
metadata:
  id: "564"
  name: "Join_transaction_Account"
spec:
  sourceSchema:
  - attributeName: "account_id"
    dataType: "string"
  - attributeName: "transaction_id"
    dataType: "string"
  - attributeName: "reason_for_payment"
    dataType: "string"
  - attributeName: "transaction_text"
    dataType: "string"
  - attributeName: "amount"
    dataType: "string"
  - attributeName: "number_of_decimals"
    dataType: "string"
  - attributeName: "direction"
    dataType: "string"
  - attributeName: "currency_code"
    dataType: "string"
  - attributeName: "booking_status"
    dataType: "string"
  - attributeName: "booking_date"
    dataType: "string"
  - attributeName: "value_date"
    dataType: "string"
  - attributeName: "is_returnable"
    dataType: "string"
  - attributeName: "__datacater_file_name"
    dataType: "string"
  - attributeName: "_account_id"
    dataType: "string"
  - attributeName: "account_holder_id"
    dataType: "string"
  - attributeName: "account_holder_name"
    dataType: "string"
  - attributeName: "iban"
    dataType: "string"
  - attributeName: "bic"
    dataType: "string"
  - attributeName: "balance"
    dataType: "string"
  - attributeName: "_currency_code"
    dataType: "string"
  - attributeName: "product_id"
    dataType: "string"
  - attributeName: "___datacater_file_name"
    dataType: "string"
  filters: []
  transformationSteps:
  - name: "Drop_Unnecessary_Columns"
    transformations:
    - attributeName: "reason_for_payment"
      transformation: "drop-column"
    - attributeName: "transaction_text"
      transformation: "drop-column"
    - attributeName: "number_of_decimals"
      transformation: "drop-column"
    - attributeName: "direction"
      transformation: "drop-column"
    - attributeName: "booking_status"
      transformation: "drop-column"
    - attributeName: "value_date"
      transformation: "drop-column"
    - attributeName: "__datacater_file_name"
      transformation: "drop-column"
    - attributeName: "account_holder_id"
      transformation: "drop-column"
    - attributeName: "bic"
      transformation: "drop-column"
    - attributeName: "product_id"
      transformation: "drop-column"
    - attributeName: "___datacater_file_name"
      transformation: "drop-column"
  - name: "Set_DataTypes"
    transformations:
    - attributeName: "account_id"
      transformation: "cast-data-type"
      transformationConfig:
        toDataType: "int"
    - attributeName: "transaction_id"
      transformation: "cast-data-type"
      transformationConfig:
        toDataType: "int"
    - attributeName: "amount"
      transformation: "cast-data-type"
      transformationConfig:
        toDataType: "int"
    - attributeName: "is_returnable"
      transformation: "cast-data-type"
      transformationConfig:
        toDataType: "boolean"
    - attributeName: "_account_id"
      transformation: "cast-data-type"
      transformationConfig:
        toDataType: "int"
    - attributeName: "balance"
      transformation: "cast-data-type"
      transformationConfig:
        toDataType: "int"
  - name: "HashIban_CapitalizeAccNam"
    transformations:
    - attributeName: "account_holder_name"
      transformation: "capitalize"
    - attributeName: "iban"
      transformation: "hash"
      transformationConfig:
        value: "SHA-1"
