apiVersion: "datacater.io/v1"
kind: "Pipeline"
metadata:
  id: "528"
  name: "Join_Transaction_Account"
spec:
  sourceSchema:
  - attributeName: "account_id"
    dataType: "string"
  - attributeName: "transaction_id"
    dataType: "string"
  - attributeName: "reason_for_payment"
    dataType: "string"
  - attributeName: "transaction_text"
    dataType: "string"
  - attributeName: "amount"
    dataType: "string"
  - attributeName: "number_of_decimals"
    dataType: "string"
  - attributeName: "direction"
    dataType: "string"
  - attributeName: "currency_code"
    dataType: "string"
  - attributeName: "booking_status"
    dataType: "string"
  - attributeName: "booking_date"
    dataType: "string"
  - attributeName: "value_date"
    dataType: "string"
  - attributeName: "is_returnable"
    dataType: "string"
  - attributeName: "__datacater_file_name"
    dataType: "string"
  - attributeName: "_account_id"
    dataType: "string"
  - attributeName: "account_holder_id"
    dataType: "string"
  - attributeName: "account_holder_name"
    dataType: "string"
  - attributeName: "iban"
    dataType: "string"
  - attributeName: "bic"
    dataType: "string"
  - attributeName: "balance"
    dataType: "string"
  - attributeName: "_currency_code"
    dataType: "string"
  - attributeName: "product_id"
    dataType: "string"
  - attributeName: "___datacater_file_name"
    dataType: "string"
  filters: []
  transformationSteps:
  - name: "Rename Columns"
    transformations:
    - attributeName: "amount"
      transformation: "user-defined-transformation"
      transformationConfig:
        code: |2-


          def transform(value, row):
            return value
    - attributeName: "_currency_code"
      transformation: "rename-column"
      transformationConfig:
        newAttributeName: "AccountCurrencyCode"
  - name: "Datatypes"
    transformations:
    - attributeName: "amount"
      transformation: "cast-data-type"
      transformationConfig:
        toDataType: "int"
    - attributeName: "number_of_decimals"
      transformation: "cast-data-type"
      transformationConfig:
        toDataType: "int"
    - attributeName: "booking_status"
      transformation: "cast-data-type"
      transformationConfig:
        toDataType: "boolean"
    - attributeName: "is_returnable"
      transformation: "cast-data-type"
      transformationConfig:
        toDataType: "boolean"
    - attributeName: "balance"
      transformation: "cast-data-type"
      transformationConfig:
        toDataType: "int"
  - name: "Drop_Unnecessary_Columns"
    transformations:
    - attributeName: "reason_for_payment"
      transformation: "drop-column"
    - attributeName: "transaction_text"
      transformation: "drop-column"
    - attributeName: "number_of_decimals"
      transformation: "drop-column"
    - attributeName: "direction"
      transformation: "drop-column"
    - attributeName: "currency_code"
      transformation: "drop-column"
    - attributeName: "booking_status"
      transformation: "drop-column"
    - attributeName: "booking_date"
      transformation: "drop-column"
    - attributeName: "value_date"
      transformation: "drop-column"
    - attributeName: "is_returnable"
      transformation: "drop-column"
    - attributeName: "__datacater_file_name"
      transformation: "drop-column"
    - attributeName: "account_holder_id"
      transformation: "drop-column"
    - attributeName: "bic"
      transformation: "drop-column"
    - attributeName: "___datacater_file_name"
      transformation: "drop-column"
  - name: "Untitled Transformation Step"
    transformations: []
